routes/web.php
<?php

use App\Http\Controllers\Api\CycleController;
use App\Http\Controllers\Api\LoginController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\JobOfferController;
use App\Http\Controllers\OfferCycleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ResponsibleController;
use App\Http\Controllers\StudentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::get('activate/user/{id}', [UserController::class, 'activarUsuario'])->name('activate.user');
Route::resource('companies', CompanyController::class);
Route::resource('jobOffers', JobOfferController::class);
Route::resource('offerCycles', OfferCycleController::class);
Route::resource('responsibles', ResponsibleController::class);
Route::resource('users', \App\Http\Controllers\UserController::class);
Route::resource('cycles', \App\Http\Controllers\CycleController::class);
Route::resource('students', StudentController::class);

Route::get('jobOffers/indexByCompany/{id}', [JobOfferController::class, 'indexByCompany'])->name('jobOffers.indexByCompany');
Route::get('responsibles/indexCyclesByResponsible/{id}', [ResponsibleController::class, 'getCyclesByResponsibleUserId'])->name('responsibles.indexCyclesByResponsible');
Route::get('responsibles/indexCyclesWithoutResponsible/{id}', [ResponsibleController::class, 'getCyclesWithoutResponsible'])->name('responsibles.indexCyclesWithoutResponsible');
Route::get('responsibles/assignResponsibleWithCycle/{responsibleId}/{cycleId}', [ResponsibleController::class, 'assignResponsibleWithCycle'])->name('responsibles.assignResponsibleWithCycle');
Route::get('responsibles/delete/{responsibleId}/{cycleId}', [ResponsibleController::class, 'delete'])->name('responsibles.delete');
Route::get('cycles/responsible/{responsibleId}', [ResponsibleController::class, 'showCyclesOfAResponsible'])->name('responsible.cycles');
Route::get('students/indexJobOffersByCycle/{cycleId}', [StudentController::class, 'indexJobOffersByCycle'])->name('cycles.indexJobOffersByCycle');
Route::get('students/indexStudentsByCycleId/{cycleId}', [StudentController::class, 'indexStudentsByCycleId'])->name('students.indexStudentsByCycleId');
//Route::delete('students/{student}/{cycleId}', [StudentController::class, 'destroy'])->name('students.destroy');
Route::get('auth/google', [LoginController::class, 'redirectToGoogle'])->name('auth.google');
Route::get('auth/google/callback', [LoginController::class, 'handleGoogleCallback'])->name('auth.callback');

require __DIR__.'/auth.php';

app/Http/Controllers/ResponsibleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cycle;
use App\Models\ResponsibleCycle;
use App\Models\User;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Foundation\Application;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ResponsibleController extends Controller
{

    public function index(Request $request): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $search = $request->input('search');

        if ($search) {
            $responsibles = User::where('role', 'responsible')
                ->where(function ($query) use ($search) {
                    $query->where('email', 'LIKE', "%$search%")
                        ->orWhere('address', 'LIKE', "%$search%")
                        ->orWhere('observations', 'LIKE', "%$search%");
                })
                ->get();
        } else {
            $responsibles = User::where('role', 'responsible')->get();
        }

        return view('responsibles.index', compact('responsibles', 'search'));
    }

    public function getCyclesByResponsibleUserId($responsibleId, Request $request): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $search = $request->input('search');

        $user = User::findOrFail($responsibleId);
        $cyclesByResponsibleUserId = $user->cycles();

        if ($search) {
            $cyclesByResponsibleUserId->where('ciclo', 'like', '%' . $search . '%');
        }

        $cyclesByResponsibleUserId = $cyclesByResponsibleUserId->paginate(10);

        $showRemoveButton = true;

        return view('cycles.indexCyclesByResponsibleUserId', compact('cyclesByResponsibleUserId', 'responsibleId', 'search','showRemoveButton'));
    }

    public function getCyclesWithoutResponsible($responsibleId): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $cyclesWithResponsibleIds = DB::table('responsible_cycles')->pluck('cycle_id')->toArray();
        $cyclesWithoutResponsible = Cycle::whereNotIn('id', $cyclesWithResponsibleIds)->paginate(10);
        return view('cycles.indexCyclesWithoutResponsible', compact('cyclesWithoutResponsible','responsibleId'));
    }

    public function assignResponsibleWithCycle($responsibleId,$cycleId): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $responsibleCycle = new ResponsibleCycle([
            'responsible_id' => $responsibleId,
            'cycle_id' => $cycleId,
        ]);
        $responsibleCycle->save();
        $cycle = Cycle::where('id',$cycleId)->first();
        return view('cycles.show', compact('cycle'));
    }

    public function delete($responsibleId,$cycleId): RedirectResponse
    {
        DB::table('responsible_cycles')
            ->where('responsible_id', $responsibleId)
            ->where('cycle_id', $cycleId)
            ->delete();
        return redirect()->route('responsibles.indexCyclesByResponsible', $responsibleId)->with('success', 'Eliminada relación entre responsable y ciclo');
    }

    public function create(): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        return view('responsibles.create');
    }

    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'email' => 'required|email|unique:users,email',
            'password' => 'required|min:8',
            'address' => 'required|string',
        ]);

        $observations = $request->input('observations') ?? 'Sin observaciones';

        $responsible = new User([
            'email' => $request->input('email'),
            'password' => bcrypt($request->input('password')),
            'address' => $request->input('address'),
            'observations' => $observations,
            'role' => 'responsible',
            'accept' => 1,
            'isActivated' => 1,
        ]);

        $responsible->save();

        do {
            $token = $responsible->createToken('Personal Access Token')->plainTextToken;
        } while (User::where('token', $token)->exists());

        $responsible->forceFill([
            'token' => $token,
        ])->save();

        return redirect()->route('responsibles.index')->with('success', 'Responsable creado correctamente');
    }

    public function show($id): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $user = User::findOrFail($id);
        return view('users.show', compact('user'));
    }

    public function edit($id): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $responsible = User::findOrFail($id);
        return view('responsibles.edit', compact('responsible'));
    }

    public function update(Request $request, $id): RedirectResponse
    {
        $responsible = User::findOrFail($id);
        $responsible->update($request->all());
        return redirect()->route('responsibles.index')->with('success', 'Responsable actualizado correctamente');
    }

    public function destroy(User $responsible): RedirectResponse
    {
        $responsible->delete();
        return redirect()->route('responsibles.index')->with('success', 'Responsable eliminado correctamente');
    }

    public function showCyclesOfAResponsible($responsibleId): View|Application|Factory|\Illuminate\Contracts\Foundation\Application {
        $cycleIds = ResponsibleCycle::where('responsible_id', $responsibleId)->pluck('cycle_id')->toArray();

        $cyclesByResponsibleUserId = Cycle::whereIn('id', $cycleIds)->paginate(10);

        $showRemoveButton = false;

        return view('cycles.indexCyclesByResponsibleUserId', compact('cyclesByResponsibleUserId', 'responsibleId','showRemoveButton'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/responsibles/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Crear Responsable') }}
        </h2>
    </x-slot>

    <div class="py-8">
        <div class="max-w-2xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
                <form action="{{ route('responsibles.store') }}" method="POST">
                    @csrf

                    <div class="mb-6">
                        <label for="email" class="block text-sm font-medium text-gray-700">Email:</label>
                        <input type="email" name="email" id="email" value="{{ old('email') }}" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" required>
                        @error('email')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="password" class="block text-sm font-medium text-gray-700">Contraseña:</label>
                        <input type="password" name="password" id="password" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" required>
                        @error('password')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="password_confirmation" class="block text-sm font-medium text-gray-700">Confirmar Contraseña:</label>
                        <input type="password" name="password_confirmation" id="password_confirmation" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" required>
                        @error('password_confirmation')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="address" class="block text-sm font-medium text-gray-700">Dirección:</label>
                        <input type="text" name="address" id="address" value="{{ old('address') }}" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" required>
                        @error('address')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="observations" class="block text-sm font-medium text-gray-700">Observaciones:</label>
                        <textarea name="observations" id="observations" rows="3" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">{{ old('observations', 'Sin observaciones') }}</textarea>
                        @error('observations')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="flex justify-end">
                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                            Guardar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/responsibles/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Editar Responsable') }}
        </h2>
    </x-slot>

    <div class="py-8">
        <div class="max-w-2xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
                <form action="{{ route('responsibles.update', $responsible->id) }}" method="POST">
                    @method('PATCH')
                    @csrf

                    <div class="mb-6">
                        <label for="email" class="block text-sm font-medium text-gray-700">Correo electrónico:</label>
                        <input type="email" name="email" id="email" value="{{ $responsible->email }}" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                        @error('email')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="address" class="block text-sm font-medium text-gray-700">Dirección:</label>
                        <input type="text" name="address" id="address" value="{{ $responsible->address }}" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                        @error('address')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="observations" class="block text-sm font-medium text-gray-700">Observaciones:</label>
                        <textarea name="observations" id="observations" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">{{ $responsible->observations }}</textarea>
                        @error('observations')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="flex justify-end">
                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                            Guardar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/responsibles/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight text-center">
            {{ __('Lista de Responsables') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="mb-4">
                <form action="{{ route('responsibles.index') }}" method="GET" class="text-center">
                    <div class="flex items-center justify-center">
                        <input type="text" name="search" placeholder="Buscar por responsable" class="mr-4 px-4 py-2 border border-gray-300 rounded-md">
                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Buscar</button>
                    </div>
                </form>
            </div>

            <div class="flex justify-end mb-4">
                <a href="{{ route('responsibles.create') }}" class="bg-yellow-400 hover:bg-yellow-500 text-white font-bold py-2 px-4 rounded">+ Nuevo responsable</a>
            </div>

            <div class="overflow-hidden bg-white shadow sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50 dark:bg-gray-800 text-center">
                    <tr>
                        <th scope="col" class="px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Email
                        </th>

                        <th scope="col" class="px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Dirección
                        </th>

                        <th scope="col" class="px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Observaciones
                        </th>

                        <th scope="col" class="px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Acciones
                        </th>
                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200 text-center">
                    @forelse($responsibles as $responsible)
                        <tr>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="text-sm text-gray-900">{{ $responsible->email }}</div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="text-sm text-gray-900">{{ $responsible->address }}</div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="text-sm text-gray-900">{{ $responsible->observations }}</div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="flex items-center justify-center">
                                    <a href="{{ route('users.show', $responsible->id) }}" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded mr-2">Ver</a>
                                    <a href="{{ route('responsibles.indexCyclesByResponsible', $responsible->id) }}" class="inline-block bg-orange-500 hover:bg-orange-700 text-white font-bold py-1 px-2 rounded mr-2">Ver ciclos</a>
                                    <a href="{{ route('responsibles.indexCyclesWithoutResponsible',$responsible->id) }}" class="inline-block bg-green-500 hover:bg-green-700 text-white font-bold py-1 px-2 rounded mr-2">+ Asignar ciclo</a>
                                    <a href="{{ route('responsibles.edit', $responsible) }}" class="inline-block bg-blue-600 hover:bg-blue-900 text-white font-bold py-1 px-2 rounded ml-1">Editar</a>
                                    <form action="{{ route('responsibles.destroy', $responsible) }}" method="POST" class="inline-block">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded ml-1">Eliminar responsable</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="4" class="px-6 py-4 whitespace-nowrap">
                                <p class="text-sm text-gray-500">No hay responsables</p>
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</x-app-layout>