routes/web.php
<?php

use App\Http\Controllers\Api\CycleController;
use App\Http\Controllers\Api\LoginController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\JobOfferController;
use App\Http\Controllers\OfferCycleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ResponsibleController;
use App\Http\Controllers\StudentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::get('activate/user/{id}', [UserController::class, 'activarUsuario'])->name('activate.user');
Route::resource('companies', CompanyController::class);
Route::resource('jobOffers', JobOfferController::class);
Route::resource('offerCycles', OfferCycleController::class);
Route::resource('responsibles', ResponsibleController::class);
Route::resource('users', \App\Http\Controllers\UserController::class);
Route::resource('cycles', \App\Http\Controllers\CycleController::class);
Route::resource('students', StudentController::class);

Route::get('jobOffers/indexByCompany/{id}', [JobOfferController::class, 'indexByCompany'])->name('jobOffers.indexByCompany');
Route::get('responsibles/indexCyclesByResponsible/{id}', [ResponsibleController::class, 'getCyclesByResponsibleUserId'])->name('responsibles.indexCyclesByResponsible');
Route::get('responsibles/indexCyclesWithoutResponsible/{id}', [ResponsibleController::class, 'getCyclesWithoutResponsible'])->name('responsibles.indexCyclesWithoutResponsible');
Route::get('responsibles/assignResponsibleWithCycle/{responsibleId}/{cycleId}', [ResponsibleController::class, 'assignResponsibleWithCycle'])->name('responsibles.assignResponsibleWithCycle');
Route::get('responsibles/delete/{responsibleId}/{cycleId}', [ResponsibleController::class, 'delete'])->name('responsibles.delete');
Route::get('cycles/responsible/{responsibleId}', [ResponsibleController::class, 'showCyclesOfAResponsible'])->name('responsible.cycles');
Route::get('students/indexJobOffersByCycle/{cycleId}', [StudentController::class, 'indexJobOffersByCycle'])->name('cycles.indexJobOffersByCycle');
Route::get('students/indexStudentsByCycleId/{cycleId}', [StudentController::class, 'indexStudentsByCycleId'])->name('students.indexStudentsByCycleId');
//Route::delete('students/{student}/{cycleId}', [StudentController::class, 'destroy'])->name('students.destroy');
Route::get('auth/google', [LoginController::class, 'redirectToGoogle'])->name('auth.google');
Route::get('auth/google/callback', [LoginController::class, 'handleGoogleCallback'])->name('auth.callback');

require __DIR__.'/auth.php';

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Company extends Model {

    use HasFactory;

    protected $fillable = [
        'user_id',
        'name',
        'cif',
        'contactName',
        'companyWeb',
    ];

    public function user(): BelongsTo {
        return $this->belongsTo(User::class,'user_id','id');
    }
}

app/Http/Controllers/Api/CompanyController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\CompanyRequest;
use App\Http\Resources\CompanyResource;
use App\Http\Resources\DefaultCollection;
use App\Mail\ActivationEmail;
use App\Models\Company;
use App\Models\User;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Symfony\Component\HttpFoundation\Response as ResponseAlias;

class CompanyController extends Controller {

    public function index(): DefaultCollection {
        $companies = Company::paginate(10);
        return new DefaultCollection($companies);
    }

    public function store(CompanyRequest $request): JsonResponse {
        try {
            DB::beginTransaction();
            $user = new User([
                'email' => $request['email'],
                'password' => bcrypt($request['password']),
                'address' => $request['address'],
                'accept' => $request['accept'],
                'role' => 'company',
                'isActivated' => 0,
            ]);
            $user->save();

            do {
                $token = $user->createToken('Personal Access Token')->plainTextToken;
            } while (User::where('token', $token)->exists());

            $user->forceFill([
                'token' => $token,
                'email_verified_at' => now(),
            ])->save();

            $company = new Company([
                'user_id' => $user->id,
                'name' => $request['name'],
                'cif' => $request['cif'],
                'contactName' => $request['contactName'],
                'companyWeb' => $request['companyWeb'],
            ]);
            $company->save();

            Mail::to($user->email)->send(new ActivationEmail($user));

            DB::commit();
            return response()->json([
                'message' => 'Company created successfully',
                'data' => new CompanyResource($company)
            ], 201);
        } catch (Exception $e) {
            DB::rollBack();
            return response()->json([
                'error' => 'Failed to create company',
                'message' => $e->getMessage()
            ], ResponseAlias::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    public function show(Company $company) {
        $companyResource = new CompanyResource($company);
        return $this->addStatus($companyResource);
    }

    public function destroy(Company $company): JsonResponse {
        try {
            $company->delete();
            return response()->json([
                'message' => 'Company deleted successfully',
                'data' => $company->id
            ]);
        } catch (Exception) {
            return response()->json([
                'error' => 'Company not found'
            ], 404);
        }
    }

    public function update(CompanyRequest $request, Company $company): JsonResponse {
        try {
            $user = $company->user;

            DB::beginTransaction();

            $company->update($request->except('password', 'accept'));

            $user->update([
                'password' => bcrypt($request->input('password')),
                'address' => $request->input('address'),
            ]);

            DB::commit();

            return response()->json([
                'message' => 'Company and user updated successfully',
                'data' => new CompanyResource($company)
            ], ResponseAlias::HTTP_OK);
        } catch (Exception $e) {
            return response()->json([
                'error' => 'Failed to update company',
                'message' => $e->getMessage()
            ], ResponseAlias::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    private function addStatus($resource) {
        $data = $resource->toArray(request());
        $data['status'] = 'success';
        return $data;
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CompanyRequest;
use App\Mail\ActivationEmail;
use App\Models\Company;
use App\Models\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Foundation\Application;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;

class CompanyController extends Controller
{
    public function index(Request $request): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $search = $request->input('search');
        $companies = Company::query()
            ->when($search, function ($query, $search) {
                return $query->where('name', 'like', '%' . $search . '%');
            })
            ->orderBy('id', 'ASC')
            ->paginate(10);

        return view('companies.index', compact('companies'));
    }


    public function create(): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        return view('companies.create');
    }

    public function store(CompanyRequest $request): RedirectResponse
    {
        try {
            DB::beginTransaction();
            $user = User::create([
                'email' => $request['email'],
                'password' => bcrypt($request['password']),
                'address' => $request['address'],
                'accept' => $request['accept'],
                'observations' => $request['observations'],
                'role' => 'company',
                'isActivated' => 0,
            ]);
            do {
                $token = $user->createToken('Personal Access Token')->plainTextToken;
            } while (User::where('token', $token)->exists());

            $user->forceFill([
                'token' => $token,
                'email_verified_at' => now(),
            ])->save();

            $company = Company::create([
                'user_id' => $user->id,
                'name' => $request['name'],
                'cif' => $request['cif'],
                'contactName' => $request['contactName'],
                'companyWeb' => $request['companyWeb'],
            ]);

            Mail::to($user->email)->send(new ActivationEmail($user));

            DB::commit();

            return redirect()->route('companies.show', $company)->with('success', 'Compañía creada correctamente');
        } catch (\Exception $e) {
            DB::rollBack();
            return redirect()->back()->withErrors($e->getMessage())->withInput();
        }
    }

    public function show(Company $company): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        return view('companies.show', compact('company'));
    }

    public function edit(Company $company): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        return view('companies.edit', compact('company'));
    }

    public function update(Request $request, Company $company): RedirectResponse
    {
        $validatedData = $request->validate([
            'name' => 'required|string|max:50',
            'cif' => [
                'required',
                'string',
                'size:9',
                'regex:/^[AB]\d{7}[0-9A-B]$/',
                'unique:companies,cif,' . $company->id,
            ],
            'contactName' => 'nullable|string|max:20',
            'companyWeb' => 'nullable|url',
        ]);

        try {
            $company->update($validatedData);
            return redirect()->route('companies.show', $company)->with('success', 'Compañía actualizada correctamente');
        } catch (\Exception $e) {
            return redirect()->back()->withErrors($e->getMessage())->withInput();
        }
    }

    public function destroy(Company $company): RedirectResponse
    {
        $user = User::where('id',$company->user_id)->first();
        $user->delete();
        return redirect()->route('companies.index')->with('success', 'Compañía eliminada correctamente');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/companies/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Crear Compañía y Usuario') }}
        </h2>
    </x-slot>

    <div class="py-8">
        <div class="max-w-2xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
                <form action="{{ route('companies.store') }}" method="POST">
                    @csrf

                    {{-- Datos del usuario --}}
                    <div class="mb-6">
                        <label for="email" class="block text-sm font-medium text-gray-700">Correo electrónico:</label>
                        <input type="email" name="email" id="email" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" autocomplete="email">
                        @error('email')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="password" class="block text-sm font-medium text-gray-700">Contraseña:</label>
                        <input type="password" name="password" id="password" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" autocomplete="current-password">
                        @error('password')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="address" class="block text-sm font-medium text-gray-700">Dirección:</label>
                        <input type="text" name="address" id="address" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" autocomplete="address">
                        @error('address')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label class="block text-sm font-medium text-gray-700">¿Acepta las condiciones de uso?</label>
                        <div class="mt-1">
                            <div class="flex items-center">
                                <input id="accept_yes" name="accept" type="radio" value="1" class="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300">
                                <label for="accept_yes" class="ml-3 block text-sm font-medium text-gray-700">Sí</label>
                            </div>
                            <div class="flex items-center mt-2">
                                <input id="accept_no" name="accept" type="radio" value="0" class="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300">
                                <label for="accept_no" class="ml-3 block text-sm font-medium text-gray-700">No</label>
                            </div>
                        </div>
                        @error('accept')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="observations" class="block text-sm font-medium text-gray-700">Observaciones:</label>
                        <textarea name="observations" id="observations" rows="3" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"></textarea>
                    </div>

                    {{-- Datos de la compañía --}}
                    <div class="mb-6">
                        <label for="company_name" class="block text-sm font-medium text-gray-700">Nombre de la Compañía:</label>
                        <input type="text" name="name" id="name" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" autocomplete="organization">
                        @error('name')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="cif" class="block text-sm font-medium text-gray-700">CIF:</label>
                        <input type="text" name="cif" id="cif" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" autocomplete="tax-id">
                        @error('cif')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="contact_name" class="block text-sm font-medium text-gray-700">Nombre de Contacto:</label>
                        <input type="text" name="contactName" id="contactName" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                        @error('contactName')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="company_web" class="block text-sm font-medium text-gray-700">Web de la Compañía:</label>
                        <input type="text" name="companyWeb" id="companyWeb" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" autocomplete="url">
                        @error('companyWeb')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="flex justify-end">
                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                            Crear Compañía y Usuario
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/companies/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Editar Compañía') }}
        </h2>
    </x-slot>

    <div class="py-8">
        <div class="max-w-2xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
                <form action="{{ route('companies.update', $company->id) }}" method="POST">
                    @method('PATCH')
                    @csrf

                    <div class="mb-6">
                        <label for="name" class="block text-sm font-medium text-gray-700">Nombre:</label>
                        <input type="text" name="name" id="name" value="{{ $company->name }}" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                        @error('name')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="cif" class="block text-sm font-medium text-gray-700">CIF:</label>
                        <input type="text" name="cif" id="cif" value="{{ $company->cif }}" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                        @error('cif')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="contactName" class="block text-sm font-medium text-gray-700">Nombre de Contacto:</label>
                        <input type="text" name="contactName" id="contactName" value="{{ $company->contactName }}" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                        @error('contactName')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="mb-6">
                        <label for="companyWeb" class="block text-sm font-medium text-gray-700">Web de la Compañía:</label>
                        <input type="text" name="companyWeb" id="companyWeb" value="{{ $company->companyWeb }}" class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                        @error('companyWeb')
                        <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="flex justify-end">
                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                            Guardar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/companies/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight text-center">
            {{ __('Listado de Compañías') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="mb-4">
                <form action="{{ route('companies.index') }}" method="GET" class="text-center">
                    <div class="flex items-center justify-center">
                        <input type="text" name="search" placeholder="Buscar por compañía" class="mr-4 px-4 py-2 border border-gray-300 rounded-md">
                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Buscar</button>
                    </div>
                </form>
            </div>

            <div class="flex justify-end mb-4">
                <a href="{{ route('companies.create') }}" class="bg-yellow-400 hover:bg-yellow-500 text-white font-bold py-2 px-4 rounded">+ Nueva empresa</a>
            </div>

            <div class="overflow-hidden bg-white shadow sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50 dark:bg-gray-800 text-center">
                    <tr>
                        <th scope="col" class="px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">
                            ID
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Nombre
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Acciones
                        </th>
                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200 text-center">
                    @forelse($companies as $company)
                        <tr>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="text-sm text-gray-900">{{ $company->id }}</div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="text-sm text-gray-900">{{ $company->name }}</div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="flex items-center justify-center">
                                    <a href="{{ route('companies.show', $company) }}" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2">Ver</a>
                                    <a href="{{ route('jobOffers.indexByCompany', $company->id) }}" class="inline-block bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded mr-2">Ver ofertas</a>
                                    <a href="{{ route('companies.edit', $company) }}" class="inline-block bg-green-500 hover:bg-green-700 text-white font-bold py-1 px-2 rounded ml-1">Editar</a>
                                    <form action="{{ route('companies.destroy', $company) }}" method="POST" class="inline-block">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded ml-1">Eliminar compañía</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="3" class="px-6 py-4 whitespace-nowrap">
                                <p class="text-sm text-gray-500">No hay compañías</p>
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            <div class="mt-6">
                {{ $companies->links() }}
            </div>
        </div>
    </div>
</x-app-layout>