routes/web.php
<?php

use App\Http\Controllers\Api\CycleController;
use App\Http\Controllers\Api\LoginController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\JobOfferController;
use App\Http\Controllers\OfferCycleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ResponsibleController;
use App\Http\Controllers\StudentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::get('activate/user/{id}', [UserController::class, 'activarUsuario'])->name('activate.user');
Route::resource('companies', CompanyController::class);
Route::resource('jobOffers', JobOfferController::class);
Route::resource('offerCycles', OfferCycleController::class);
Route::resource('responsibles', ResponsibleController::class);
Route::resource('users', \App\Http\Controllers\UserController::class);
Route::resource('cycles', \App\Http\Controllers\CycleController::class);
Route::resource('students', StudentController::class);

Route::get('jobOffers/indexByCompany/{id}', [JobOfferController::class, 'indexByCompany'])->name('jobOffers.indexByCompany');
Route::get('responsibles/indexCyclesByResponsible/{id}', [ResponsibleController::class, 'getCyclesByResponsibleUserId'])->name('responsibles.indexCyclesByResponsible');
Route::get('responsibles/indexCyclesWithoutResponsible/{id}', [ResponsibleController::class, 'getCyclesWithoutResponsible'])->name('responsibles.indexCyclesWithoutResponsible');
Route::get('responsibles/assignResponsibleWithCycle/{responsibleId}/{cycleId}', [ResponsibleController::class, 'assignResponsibleWithCycle'])->name('responsibles.assignResponsibleWithCycle');
Route::get('responsibles/delete/{responsibleId}/{cycleId}', [ResponsibleController::class, 'delete'])->name('responsibles.delete');
Route::get('cycles/responsible/{responsibleId}', [ResponsibleController::class, 'showCyclesOfAResponsible'])->name('responsible.cycles');
Route::get('students/indexJobOffersByCycle/{cycleId}', [StudentController::class, 'indexJobOffersByCycle'])->name('cycles.indexJobOffersByCycle');
Route::get('students/indexStudentsByCycleId/{cycleId}', [StudentController::class, 'indexStudentsByCycleId'])->name('students.indexStudentsByCycleId');
//Route::delete('students/{student}/{cycleId}', [StudentController::class, 'destroy'])->name('students.destroy');
Route::get('auth/google', [LoginController::class, 'redirectToGoogle'])->name('auth.google');
Route::get('auth/google/callback', [LoginController::class, 'handleGoogleCallback'])->name('auth.callback');

require __DIR__.'/auth.php';

app/Models/Cycle.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Cycle extends Model {

    use HasFactory;

    protected $fillable = [
        'ciclo',
        'departamento',
        'tipo',
        'normativa',
        'titol',
        'rd',
        'rd2',
        'vliteral',
        'cliteral',
        'horasFct',
        'acronim',
        'llocTreball',
        'dataSignaturaDual',
    ];

    public function professionalFamily(): BelongsTo {
        return $this->belongsTo(ProfessionalFamily::class,'departamento','id');
    }

    public function responsible(): BelongsToMany {
        return $this->belongsToMany(User::class,'responsible_cycles','cycle_id','responsible_id');
    }

    public function students(): BelongsToMany {
        return $this->belongsToMany(Student::class, 'student_cycles', 'cycle_id', 'student_id');
    }

    public function jobOffer(): BelongsToMany {
        return $this->belongsToMany(JobOffer::class, 'offer_cycles', 'cycle_id', 'job_offer_id');
    }
}

app/Http/Controllers/Api/CycleController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\CycleResource;
use App\Http\Resources\DefaultCollection;
use App\Models\Cycle;
use App\Models\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Foundation\Application;

class CycleController extends Controller {

    public function index(): DefaultCollection {
        $cycles = Cycle::paginate(10);
        return new DefaultCollection($cycles);
    }

    public function show(Cycle $cycle) {
        $cycleResource = new CycleResource($cycle);
        return $this->addStatus($cycleResource);
    }

    private function addStatus($resource) {
        $data = $resource->toArray(request());
        $data['status'] = 'success';
        return $data;
    }
}

app/Http/Controllers/CycleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cycle;
use App\Models\ResponsibleCycle;
use App\Models\StudentCycle;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Foundation\Application;
use Illuminate\Http\Request;

class CycleController extends Controller
{
    public function index(Request $request): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $search = $request->input('search');

        if ($search) {
            $cycles = Cycle::where('ciclo', 'LIKE', "%$search%")->paginate(10);
        } else {
            $cycles = Cycle::paginate(10);
        }

        return view('cycles.index', compact('cycles', 'search'));
    }

    public function show($cycleId): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $cycle = Cycle::where('id',$cycleId)->first();
        return view('cycles.show', compact('cycle'));
    }

    public function getCyclesOfResponsible($responsibleId): View|Application|Factory|\Illuminate\Contracts\Foundation\Application|null
    {
        try {
            $cycleIds = ResponsibleCycle::where('responsible_id', $responsibleId)->pluck('cycle_id');
            $cyclesByResponsibleUserId = Cycle::whereIn('id', $cycleIds)->get();

            return view('cycles.indexCyclesByResponsibleUserId', compact('cyclesByResponsibleUserId','responsibleId'));
        } catch (Exception $e) {
            return null;
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/cycles/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Lista de Ciclos') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="mb-4">
                <form action="{{ route('cycles.index') }}" method="GET" class="text-center">
                    <div class="flex items-center justify-center">
                        <input type="text" name="search" placeholder="Buscar ciclo" class="mr-4 px-4 py-2 border border-gray-300 rounded-md">
                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Buscar</button>
                    </div>
                </form>
            </div>

            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50 dark:bg-gray-800 text-center">
                    <tr>
                        <th scope="col" class="px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">ID</th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">Nombre</th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">Acciones</th>
                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200 text-center">
                    @foreach($cycles as $cycle)
                        <tr>
                            <td class="px-6 py-4 whitespace-nowrap">{{ $cycle->id }}</td>
                            <td class="px-6 py-4 whitespace-nowrap">{{ $cycle->ciclo }}</td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="flex items-center justify-center">
                                    <a href="{{ route('cycles.show', $cycle) }}" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2">Ver</a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <div class="mt-6">
                {{ $cycles->links() }}
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/cycles/indexCyclesByResponsibleUserId.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Lista de Ciclos sin un Responsable Asignado') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
                <form action="{{ route('responsibles.indexCyclesByResponsible', $responsibleId) }}" method="GET" class="text-center mb-6">
                    <div class="flex items-center justify-center">
                        <input type="text" name="search" placeholder="Buscar ciclo" class="mr-4 px-4 py-2 border border-gray-300 rounded-md">
                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Buscar</button>
                    </div>
                </form>

                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-blue-500 text-white">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium">ID</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium">Nombre</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium">Acciones</th>
                        </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">
                        @foreach($cyclesByResponsibleUserId as $cycle)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">{{ $cycle->id }}</td>
                                <td class="px-6 py-4 whitespace-nowrap">{{ $cycle->ciclo }}</td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="flex items-center justify-center">
                                        <a href="{{ route('cycles.show', $cycle) }}" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2">Ver</a>
                                        @if($showRemoveButton)
                                            <a href="{{ route('responsibles.delete', ['responsibleId' => $responsibleId, 'cycleId' => $cycle->id]) }}" class="inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded mr-2">Quitar</a>
                                        @endif
                                        <a href="{{ route('students.indexStudentsByCycleId', $cycle->id) }}" class="inline-block bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded mr-2">Ver alumnos</a>
                                        <a href="{{ route('cycles.indexJobOffersByCycle', $cycle->id) }}" class="inline-block bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mr-2">Ver Ofertas de Trabajo</a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="mt-6">
                    {{ $cyclesByResponsibleUserId->links() }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/cycles/indexCyclesWithoutResponsible.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Lista de Ciclos sin un Responsable Asignado') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg text-center">
                <div class="p-6 sm:px-20 bg-white border-b border-gray-200">
                    <div class="flex flex-col">
                        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                                    <table class="min-w-full divide-y divide-gray-200">
                                        <thead class="bg-gray-50">
                                        <tr>
                                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                ID
                                            </th>
                                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Nombre
                                            </th>
                                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Acciones
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody class="bg-white divide-y divide-gray-200">
                                        @foreach($cyclesWithoutResponsible as $cycle)
                                            <tr>
                                                <td class="px-6 py-4 whitespace-nowrap">
                                                    <div class="text-sm text-gray-900">{{ $cycle->id }}</div>
                                                </td>
                                                <td class="px-6 py-4 whitespace-nowrap">
                                                    <div class="text-sm text-gray-900">{{ $cycle->ciclo }}</div>
                                                </td>
                                                <td class="px-6 py-4 whitespace-nowrap">
                                                    <div class="flex items-center justify-center">
                                                        <a href="{{ route('cycles.show', $cycle) }}" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2">Ver</a>
                                                        <a href="{{ route('responsibles.assignResponsibleWithCycle', ['responsibleId' => $responsibleId, 'cycleId' => $cycle->id]) }}" class="inline-block bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mr-2">Asignar</a>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mt-6">
                {{ $cyclesWithoutResponsible->links() }}
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/cycles/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Detalles del Ciclo') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="p-6 sm:px-20 bg-white border-b border-gray-200 dark:bg-gray-800">
                    <div class="flex flex-col">
                        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                                <div class="shadow overflow-hidden border-b border-gray-200 dark:border-gray-700 sm:rounded-lg">
                                    <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                                        <tbody class="bg-white divide-y divide-gray-200 dark:bg-gray-800">
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                ID
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->id }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                Nombre del Ciclo
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->ciclo }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                Departamento
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->departamento }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                Tipo
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->tipo }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                Normativa
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->normativa }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                Título
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->titol }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                RD
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->rd }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                RD2
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->rd2 }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                Vliteral
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->vliteral }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                Cliteral
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->cliteral }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                HorasFct
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->horasFct }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                Acronim
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->acronim }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                LlocTreball
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->llocTreball }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                DataSignaturaDual
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                {{ $cycle->dataSignaturaDual }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-200">
                                                Email del Responsable
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                @if($cycle->Responsible->first())
                                                    <a href="{{ route('users.show', $cycle->Responsible->first()) }}" class="underline hover:text-blue-500">{{ $cycle->Responsible->first()->email }}</a>
                                                @else
                                                    Sin responsable asignado
                                                @endif
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>